/* automatically generated by rust-bindgen 0.72.1 */

// @generated by gen-bindings.sh from the libFLAC 1.5.0 headers in
// include/FLAC/ — do not edit. Regenerate with bindgen 0.72.1 on a unix host.
//
// `--allowlist-file` restricts this to items declared by libFLAC's own headers,
// and the calls that take a C `FILE*` are left out with the type they need.
#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case)]

#[repr(C)]
#[derive(Copy, Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct __BindgenBitfieldUnit<Storage> {
    storage: Storage,
}
impl<Storage> __BindgenBitfieldUnit<Storage> {
    #[inline]
    pub const fn new(storage: Storage) -> Self {
        Self { storage }
    }
}
impl<Storage> __BindgenBitfieldUnit<Storage>
where
    Storage: AsRef<[u8]> + AsMut<[u8]>,
{
    #[inline]
    fn extract_bit(byte: u8, index: usize) -> bool {
        let bit_index = if cfg!(target_endian = "big") { 7 - (index % 8) } else { index % 8 };
        let mask = 1 << bit_index;
        byte & mask == mask
    }
    #[inline]
    pub fn get_bit(&self, index: usize) -> bool {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = self.storage.as_ref()[byte_index];
        Self::extract_bit(byte, index)
    }
    #[inline]
    pub unsafe fn raw_get_bit(this: *const Self, index: usize) -> bool {
        debug_assert!(index / 8 < core::mem::size_of::<Storage>());
        let byte_index = index / 8;
        let byte = unsafe {
            *(core::ptr::addr_of!((*this).storage) as *const u8).offset(byte_index as isize)
        };
        Self::extract_bit(byte, index)
    }
    #[inline]
    fn change_bit(byte: u8, index: usize, val: bool) -> u8 {
        let bit_index = if cfg!(target_endian = "big") { 7 - (index % 8) } else { index % 8 };
        let mask = 1 << bit_index;
        if val {
            byte | mask
        } else {
            byte & !mask
        }
    }
    #[inline]
    pub fn set_bit(&mut self, index: usize, val: bool) {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = &mut self.storage.as_mut()[byte_index];
        *byte = Self::change_bit(*byte, index, val);
    }
    #[inline]
    pub unsafe fn raw_set_bit(this: *mut Self, index: usize, val: bool) {
        debug_assert!(index / 8 < core::mem::size_of::<Storage>());
        let byte_index = index / 8;
        let byte = unsafe {
            (core::ptr::addr_of_mut!((*this).storage) as *mut u8).offset(byte_index as isize)
        };
        unsafe { *byte = Self::change_bit(*byte, index, val) };
    }
    #[inline]
    pub fn get(&self, bit_offset: usize, bit_width: u8) -> u64 {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        let mut val = 0;
        for i in 0..(bit_width as usize) {
            if self.get_bit(i + bit_offset) {
                let index =
                    if cfg!(target_endian = "big") { bit_width as usize - 1 - i } else { i };
                val |= 1 << index;
            }
        }
        val
    }
    #[inline]
    pub unsafe fn raw_get(this: *const Self, bit_offset: usize, bit_width: u8) -> u64 {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < core::mem::size_of::<Storage>());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= core::mem::size_of::<Storage>());
        let mut val = 0;
        for i in 0..(bit_width as usize) {
            if unsafe { Self::raw_get_bit(this, i + bit_offset) } {
                let index =
                    if cfg!(target_endian = "big") { bit_width as usize - 1 - i } else { i };
                val |= 1 << index;
            }
        }
        val
    }
    #[inline]
    pub fn set(&mut self, bit_offset: usize, bit_width: u8, val: u64) {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        for i in 0..(bit_width as usize) {
            let mask = 1 << i;
            let val_bit_is_set = val & mask == mask;
            let index = if cfg!(target_endian = "big") { bit_width as usize - 1 - i } else { i };
            self.set_bit(index + bit_offset, val_bit_is_set);
        }
    }
    #[inline]
    pub unsafe fn raw_set(this: *mut Self, bit_offset: usize, bit_width: u8, val: u64) {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < core::mem::size_of::<Storage>());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= core::mem::size_of::<Storage>());
        for i in 0..(bit_width as usize) {
            let mask = 1 << i;
            let val_bit_is_set = val & mask == mask;
            let index = if cfg!(target_endian = "big") { bit_width as usize - 1 - i } else { i };
            unsafe { Self::raw_set_bit(this, index + bit_offset, val_bit_is_set) };
        }
    }
}
pub const FLAC_API_VERSION_CURRENT: u32 = 14;
pub const FLAC_API_VERSION_REVISION: u32 = 0;
pub const FLAC_API_VERSION_AGE: u32 = 0;
pub const FLAC__MAX_METADATA_TYPE_CODE: u32 = 126;
pub const FLAC__MIN_BLOCK_SIZE: u32 = 16;
pub const FLAC__MAX_BLOCK_SIZE: u32 = 65535;
pub const FLAC__SUBSET_MAX_BLOCK_SIZE_48000HZ: u32 = 4608;
pub const FLAC__MAX_CHANNELS: u32 = 8;
pub const FLAC__MIN_BITS_PER_SAMPLE: u32 = 4;
pub const FLAC__MAX_BITS_PER_SAMPLE: u32 = 32;
pub const FLAC__REFERENCE_CODEC_MAX_BITS_PER_SAMPLE: u32 = 32;
pub const FLAC__MAX_SAMPLE_RATE: u32 = 1048575;
pub const FLAC__MAX_LPC_ORDER: u32 = 32;
pub const FLAC__SUBSET_MAX_LPC_ORDER_48000HZ: u32 = 12;
pub const FLAC__MIN_QLP_COEFF_PRECISION: u32 = 5;
pub const FLAC__MAX_QLP_COEFF_PRECISION: u32 = 15;
pub const FLAC__MAX_FIXED_ORDER: u32 = 4;
pub const FLAC__MAX_RICE_PARTITION_ORDER: u32 = 15;
pub const FLAC__SUBSET_MAX_RICE_PARTITION_ORDER: u32 = 8;
pub const FLAC__STREAM_SYNC_LENGTH: u32 = 4;
pub const FLAC__STREAM_METADATA_STREAMINFO_LENGTH: u32 = 34;
pub const FLAC__STREAM_METADATA_SEEKPOINT_LENGTH: u32 = 18;
pub const FLAC__STREAM_METADATA_HEADER_LENGTH: u32 = 4;
pub const FLAC__STREAM_DECODER_GET_LINK_LENGTHS_INVALID: i32 = -1;
pub const FLAC__STREAM_DECODER_GET_LINK_LENGTHS_NOT_INDEXED: i32 = -2;
pub const FLAC__STREAM_DECODER_GET_LINK_LENGTHS_MEMORY_ALLOCATION_ERROR: i32 = -3;
pub const FLAC__STREAM_ENCODER_SET_NUM_THREADS_OK: u32 = 0;
pub const FLAC__STREAM_ENCODER_SET_NUM_THREADS_NOT_COMPILED_WITH_MULTITHREADING_ENABLED: u32 = 1;
pub const FLAC__STREAM_ENCODER_SET_NUM_THREADS_ALREADY_INITIALIZED: u32 = 2;
pub const FLAC__STREAM_ENCODER_SET_NUM_THREADS_TOO_MANY_THREADS: u32 = 3;
extern "C" {
    pub static mut FLAC_API_SUPPORTS_OGG_FLAC: ::std::os::raw::c_int;
}
pub type FLAC__int8 = i8;
pub type FLAC__uint8 = u8;
pub type FLAC__int16 = i16;
pub type FLAC__int32 = i32;
pub type FLAC__int64 = i64;
pub type FLAC__uint16 = u16;
pub type FLAC__uint32 = u32;
pub type FLAC__uint64 = u64;
pub type FLAC__bool = ::std::os::raw::c_int;
pub type FLAC__byte = FLAC__uint8;
extern "C" {
    pub static mut FLAC__VERSION_STRING: *const ::std::os::raw::c_char;
}
extern "C" {
    pub static mut FLAC__VENDOR_STRING: *const ::std::os::raw::c_char;
}
extern "C" {
    pub static FLAC__STREAM_SYNC_STRING: [FLAC__byte; 4usize];
}
extern "C" {
    pub static FLAC__STREAM_SYNC: u32;
}
extern "C" {
    pub static FLAC__STREAM_SYNC_LEN: u32;
}
pub const FLAC__EntropyCodingMethodType_FLAC__ENTROPY_CODING_METHOD_PARTITIONED_RICE:
    FLAC__EntropyCodingMethodType = 0;
pub const FLAC__EntropyCodingMethodType_FLAC__ENTROPY_CODING_METHOD_PARTITIONED_RICE2:
    FLAC__EntropyCodingMethodType = 1;
pub type FLAC__EntropyCodingMethodType = ::std::os::raw::c_uint;
extern "C" {
    pub static FLAC__EntropyCodingMethodTypeString: [*const ::std::os::raw::c_char; 0usize];
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FLAC__EntropyCodingMethod_PartitionedRiceContents {
    pub parameters: *mut u32,
    pub raw_bits: *mut u32,
    pub capacity_by_order: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FLAC__EntropyCodingMethod_PartitionedRiceContents"]
        [::std::mem::size_of::<FLAC__EntropyCodingMethod_PartitionedRiceContents>() - 24usize];
    ["Alignment of FLAC__EntropyCodingMethod_PartitionedRiceContents"]
        [::std::mem::align_of::<FLAC__EntropyCodingMethod_PartitionedRiceContents>() - 8usize];
    ["Offset of field: FLAC__EntropyCodingMethod_PartitionedRiceContents::parameters"][::std::mem::offset_of!(
        FLAC__EntropyCodingMethod_PartitionedRiceContents,
        parameters
    ) - 0usize];
    ["Offset of field: FLAC__EntropyCodingMethod_PartitionedRiceContents::raw_bits"][::std::mem::offset_of!(
        FLAC__EntropyCodingMethod_PartitionedRiceContents,
        raw_bits
    ) - 8usize];
    ["Offset of field: FLAC__EntropyCodingMethod_PartitionedRiceContents::capacity_by_order"][::std::mem::offset_of!(
        FLAC__EntropyCodingMethod_PartitionedRiceContents,
        capacity_by_order
    )
        - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FLAC__EntropyCodingMethod_PartitionedRice {
    pub order: u32,
    pub contents: *const FLAC__EntropyCodingMethod_PartitionedRiceContents,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FLAC__EntropyCodingMethod_PartitionedRice"]
        [::std::mem::size_of::<FLAC__EntropyCodingMethod_PartitionedRice>() - 16usize];
    ["Alignment of FLAC__EntropyCodingMethod_PartitionedRice"]
        [::std::mem::align_of::<FLAC__EntropyCodingMethod_PartitionedRice>() - 8usize];
    ["Offset of field: FLAC__EntropyCodingMethod_PartitionedRice::order"]
        [::std::mem::offset_of!(FLAC__EntropyCodingMethod_PartitionedRice, order) - 0usize];
    ["Offset of field: FLAC__EntropyCodingMethod_PartitionedRice::contents"]
        [::std::mem::offset_of!(FLAC__EntropyCodingMethod_PartitionedRice, contents) - 8usize];
};
extern "C" {
    pub static FLAC__ENTROPY_CODING_METHOD_PARTITIONED_RICE_ORDER_LEN: u32;
}
extern "C" {
    pub static FLAC__ENTROPY_CODING_METHOD_PARTITIONED_RICE_PARAMETER_LEN: u32;
}
extern "C" {
    pub static FLAC__ENTROPY_CODING_METHOD_PARTITIONED_RICE2_PARAMETER_LEN: u32;
}
extern "C" {
    pub static FLAC__ENTROPY_CODING_METHOD_PARTITIONED_RICE_RAW_LEN: u32;
}
extern "C" {
    pub static FLAC__ENTROPY_CODING_METHOD_PARTITIONED_RICE_ESCAPE_PARAMETER: u32;
}
extern "C" {
    pub static FLAC__ENTROPY_CODING_METHOD_PARTITIONED_RICE2_ESCAPE_PARAMETER: u32;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FLAC__EntropyCodingMethod {
    pub type_: FLAC__EntropyCodingMethodType,
    pub data: FLAC__EntropyCodingMethod__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union FLAC__EntropyCodingMethod__bindgen_ty_1 {
    pub partitioned_rice: FLAC__EntropyCodingMethod_PartitionedRice,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FLAC__EntropyCodingMethod__bindgen_ty_1"]
        [::std::mem::size_of::<FLAC__EntropyCodingMethod__bindgen_ty_1>() - 16usize];
    ["Alignment of FLAC__EntropyCodingMethod__bindgen_ty_1"]
        [::std::mem::align_of::<FLAC__EntropyCodingMethod__bindgen_ty_1>() - 8usize];
    ["Offset of field: FLAC__EntropyCodingMethod__bindgen_ty_1::partitioned_rice"][::std::mem::offset_of!(
        FLAC__EntropyCodingMethod__bindgen_ty_1,
        partitioned_rice
    ) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FLAC__EntropyCodingMethod"]
        [::std::mem::size_of::<FLAC__EntropyCodingMethod>() - 24usize];
    ["Alignment of FLAC__EntropyCodingMethod"]
        [::std::mem::align_of::<FLAC__EntropyCodingMethod>() - 8usize];
    ["Offset of field: FLAC__EntropyCodingMethod::type_"]
        [::std::mem::offset_of!(FLAC__EntropyCodingMethod, type_) - 0usize];
    ["Offset of field: FLAC__EntropyCodingMethod::data"]
        [::std::mem::offset_of!(FLAC__EntropyCodingMethod, data) - 8usize];
};
extern "C" {
    pub static FLAC__ENTROPY_CODING_METHOD_TYPE_LEN: u32;
}
pub const FLAC__SubframeType_FLAC__SUBFRAME_TYPE_CONSTANT: FLAC__SubframeType = 0;
pub const FLAC__SubframeType_FLAC__SUBFRAME_TYPE_VERBATIM: FLAC__SubframeType = 1;
pub const FLAC__SubframeType_FLAC__SUBFRAME_TYPE_FIXED: FLAC__SubframeType = 2;
pub const FLAC__SubframeType_FLAC__SUBFRAME_TYPE_LPC: FLAC__SubframeType = 3;
pub type FLAC__SubframeType = ::std::os::raw::c_uint;
extern "C" {
    pub static FLAC__SubframeTypeString: [*const ::std::os::raw::c_char; 0usize];
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FLAC__Subframe_Constant {
    pub value: FLAC__int64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FLAC__Subframe_Constant"][::std::mem::size_of::<FLAC__Subframe_Constant>() - 8usize];
    ["Alignment of FLAC__Subframe_Constant"]
        [::std::mem::align_of::<FLAC__Subframe_Constant>() - 8usize];
    ["Offset of field: FLAC__Subframe_Constant::value"]
        [::std::mem::offset_of!(FLAC__Subframe_Constant, value) - 0usize];
};
pub const FLAC__VerbatimSubframeDataType_FLAC__VERBATIM_SUBFRAME_DATA_TYPE_INT32:
    FLAC__VerbatimSubframeDataType = 0;
pub const FLAC__VerbatimSubframeDataType_FLAC__VERBATIM_SUBFRAME_DATA_TYPE_INT64:
    FLAC__VerbatimSubframeDataType = 1;
pub type FLAC__VerbatimSubframeDataType = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FLAC__Subframe_Verbatim {
    pub data: FLAC__Subframe_Verbatim__bindgen_ty_1,
    pub data_type: FLAC__VerbatimSubframeDataType,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union FLAC__Subframe_Verbatim__bindgen_ty_1 {
    pub int32: *const FLAC__int32,
    pub int64: *const FLAC__int64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FLAC__Subframe_Verbatim__bindgen_ty_1"]
        [::std::mem::size_of::<FLAC__Subframe_Verbatim__bindgen_ty_1>() - 8usize];
    ["Alignment of FLAC__Subframe_Verbatim__bindgen_ty_1"]
        [::std::mem::align_of::<FLAC__Subframe_Verbatim__bindgen_ty_1>() - 8usize];
    ["Offset of field: FLAC__Subframe_Verbatim__bindgen_ty_1::int32"]
        [::std::mem::offset_of!(FLAC__Subframe_Verbatim__bindgen_ty_1, int32) - 0usize];
    ["Offset of field: FLAC__Subframe_Verbatim__bindgen_ty_1::int64"]
        [::std::mem::offset_of!(FLAC__Subframe_Verbatim__bindgen_ty_1, int64) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FLAC__Subframe_Verbatim"][::std::mem::size_of::<FLAC__Subframe_Verbatim>() - 16usize];
    ["Alignment of FLAC__Subframe_Verbatim"]
        [::std::mem::align_of::<FLAC__Subframe_Verbatim>() - 8usize];
    ["Offset of field: FLAC__Subframe_Verbatim::data"]
        [::std::mem::offset_of!(FLAC__Subframe_Verbatim, data) - 0usize];
    ["Offset of field: FLAC__Subframe_Verbatim::data_type"]
        [::std::mem::offset_of!(FLAC__Subframe_Verbatim, data_type) - 8usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FLAC__Subframe_Fixed {
    pub entropy_coding_method: FLAC__EntropyCodingMethod,
    pub order: u32,
    pub warmup: [FLAC__int64; 4usize],
    pub residual: *const FLAC__int32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FLAC__Subframe_Fixed"][::std::mem::size_of::<FLAC__Subframe_Fixed>() - 72usize];
    ["Alignment of FLAC__Subframe_Fixed"][::std::mem::align_of::<FLAC__Subframe_Fixed>() - 8usize];
    ["Offset of field: FLAC__Subframe_Fixed::entropy_coding_method"]
        [::std::mem::offset_of!(FLAC__Subframe_Fixed, entropy_coding_method) - 0usize];
    ["Offset of field: FLAC__Subframe_Fixed::order"]
        [::std::mem::offset_of!(FLAC__Subframe_Fixed, order) - 24usize];
    ["Offset of field: FLAC__Subframe_Fixed::warmup"]
        [::std::mem::offset_of!(FLAC__Subframe_Fixed, warmup) - 32usize];
    ["Offset of field: FLAC__Subframe_Fixed::residual"]
        [::std::mem::offset_of!(FLAC__Subframe_Fixed, residual) - 64usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FLAC__Subframe_LPC {
    pub entropy_coding_method: FLAC__EntropyCodingMethod,
    pub order: u32,
    pub qlp_coeff_precision: u32,
    pub quantization_level: ::std::os::raw::c_int,
    pub qlp_coeff: [FLAC__int32; 32usize],
    pub warmup: [FLAC__int64; 32usize],
    pub residual: *const FLAC__int32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FLAC__Subframe_LPC"][::std::mem::size_of::<FLAC__Subframe_LPC>() - 432usize];
    ["Alignment of FLAC__Subframe_LPC"][::std::mem::align_of::<FLAC__Subframe_LPC>() - 8usize];
    ["Offset of field: FLAC__Subframe_LPC::entropy_coding_method"]
        [::std::mem::offset_of!(FLAC__Subframe_LPC, entropy_coding_method) - 0usize];
    ["Offset of field: FLAC__Subframe_LPC::order"]
        [::std::mem::offset_of!(FLAC__Subframe_LPC, order) - 24usize];
    ["Offset of field: FLAC__Subframe_LPC::qlp_coeff_precision"]
        [::std::mem::offset_of!(FLAC__Subframe_LPC, qlp_coeff_precision) - 28usize];
    ["Offset of field: FLAC__Subframe_LPC::quantization_level"]
        [::std::mem::offset_of!(FLAC__Subframe_LPC, quantization_level) - 32usize];
    ["Offset of field: FLAC__Subframe_LPC::qlp_coeff"]
        [::std::mem::offset_of!(FLAC__Subframe_LPC, qlp_coeff) - 36usize];
    ["Offset of field: FLAC__Subframe_LPC::warmup"]
        [::std::mem::offset_of!(FLAC__Subframe_LPC, warmup) - 168usize];
    ["Offset of field: FLAC__Subframe_LPC::residual"]
        [::std::mem::offset_of!(FLAC__Subframe_LPC, residual) - 424usize];
};
extern "C" {
    pub static FLAC__SUBFRAME_LPC_QLP_COEFF_PRECISION_LEN: u32;
}
extern "C" {
    pub static FLAC__SUBFRAME_LPC_QLP_SHIFT_LEN: u32;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FLAC__Subframe {
    pub type_: FLAC__SubframeType,
    pub data: FLAC__Subframe__bindgen_ty_1,
    pub wasted_bits: u32,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union FLAC__Subframe__bindgen_ty_1 {
    pub constant: FLAC__Subframe_Constant,
    pub fixed: FLAC__Subframe_Fixed,
    pub lpc: FLAC__Subframe_LPC,
    pub verbatim: FLAC__Subframe_Verbatim,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FLAC__Subframe__bindgen_ty_1"]
        [::std::mem::size_of::<FLAC__Subframe__bindgen_ty_1>() - 432usize];
    ["Alignment of FLAC__Subframe__bindgen_ty_1"]
        [::std::mem::align_of::<FLAC__Subframe__bindgen_ty_1>() - 8usize];
    ["Offset of field: FLAC__Subframe__bindgen_ty_1::constant"]
        [::std::mem::offset_of!(FLAC__Subframe__bindgen_ty_1, constant) - 0usize];
    ["Offset of field: FLAC__Subframe__bindgen_ty_1::fixed"]
        [::std::mem::offset_of!(FLAC__Subframe__bindgen_ty_1, fixed) - 0usize];
    ["Offset of field: FLAC__Subframe__bindgen_ty_1::lpc"]
        [::std::mem::offset_of!(FLAC__Subframe__bindgen_ty_1, lpc) - 0usize];
    ["Offset of field: FLAC__Subframe__bindgen_ty_1::verbatim"]
        [::std::mem::offset_of!(FLAC__Subframe__bindgen_ty_1, verbatim) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FLAC__Subframe"][::std::mem::size_of::<FLAC__Subframe>() - 448usize];
    ["Alignment of FLAC__Subframe"][::std::mem::align_of::<FLAC__Subframe>() - 8usize];
    ["Offset of field: FLAC__Subframe::type_"]
        [::std::mem::offset_of!(FLAC__Subframe, type_) - 0usize];
    ["Offset of field: FLAC__Subframe::data"]
        [::std::mem::offset_of!(FLAC__Subframe, data) - 8usize];
    ["Offset of field: FLAC__Subframe::wasted_bits"]
        [::std::mem::offset_of!(FLAC__Subframe, wasted_bits) - 440usize];
};
extern "C" {
    pub static FLAC__SUBFRAME_ZERO_PAD_LEN: u32;
}
extern "C" {
    pub static FLAC__SUBFRAME_TYPE_LEN: u32;
}
extern "C" {
    pub static FLAC__SUBFRAME_WASTED_BITS_FLAG_LEN: u32;
}
extern "C" {
    pub static FLAC__SUBFRAME_TYPE_CONSTANT_BYTE_ALIGNED_MASK: u32;
}
extern "C" {
    pub static FLAC__SUBFRAME_TYPE_VERBATIM_BYTE_ALIGNED_MASK: u32;
}
extern "C" {
    pub static FLAC__SUBFRAME_TYPE_FIXED_BYTE_ALIGNED_MASK: u32;
}
extern "C" {
    pub static FLAC__SUBFRAME_TYPE_LPC_BYTE_ALIGNED_MASK: u32;
}
pub const FLAC__ChannelAssignment_FLAC__CHANNEL_ASSIGNMENT_INDEPENDENT: FLAC__ChannelAssignment = 0;
pub const FLAC__ChannelAssignment_FLAC__CHANNEL_ASSIGNMENT_LEFT_SIDE: FLAC__ChannelAssignment = 1;
pub const FLAC__ChannelAssignment_FLAC__CHANNEL_ASSIGNMENT_RIGHT_SIDE: FLAC__ChannelAssignment = 2;
pub const FLAC__ChannelAssignment_FLAC__CHANNEL_ASSIGNMENT_MID_SIDE: FLAC__ChannelAssignment = 3;
pub type FLAC__ChannelAssignment = ::std::os::raw::c_uint;
extern "C" {
    pub static FLAC__ChannelAssignmentString: [*const ::std::os::raw::c_char; 0usize];
}
pub const FLAC__FrameNumberType_FLAC__FRAME_NUMBER_TYPE_FRAME_NUMBER: FLAC__FrameNumberType = 0;
pub const FLAC__FrameNumberType_FLAC__FRAME_NUMBER_TYPE_SAMPLE_NUMBER: FLAC__FrameNumberType = 1;
pub type FLAC__FrameNumberType = ::std::os::raw::c_uint;
extern "C" {
    pub static FLAC__FrameNumberTypeString: [*const ::std::os::raw::c_char; 0usize];
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FLAC__FrameHeader {
    pub blocksize: u32,
    pub sample_rate: u32,
    pub channels: u32,
    pub channel_assignment: FLAC__ChannelAssignment,
    pub bits_per_sample: u32,
    pub number_type: FLAC__FrameNumberType,
    pub number: FLAC__FrameHeader__bindgen_ty_1,
    pub crc: FLAC__uint8,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union FLAC__FrameHeader__bindgen_ty_1 {
    pub frame_number: FLAC__uint32,
    pub sample_number: FLAC__uint64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FLAC__FrameHeader__bindgen_ty_1"]
        [::std::mem::size_of::<FLAC__FrameHeader__bindgen_ty_1>() - 8usize];
    ["Alignment of FLAC__FrameHeader__bindgen_ty_1"]
        [::std::mem::align_of::<FLAC__FrameHeader__bindgen_ty_1>() - 8usize];
    ["Offset of field: FLAC__FrameHeader__bindgen_ty_1::frame_number"]
        [::std::mem::offset_of!(FLAC__FrameHeader__bindgen_ty_1, frame_number) - 0usize];
    ["Offset of field: FLAC__FrameHeader__bindgen_ty_1::sample_number"]
        [::std::mem::offset_of!(FLAC__FrameHeader__bindgen_ty_1, sample_number) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FLAC__FrameHeader"][::std::mem::size_of::<FLAC__FrameHeader>() - 40usize];
    ["Alignment of FLAC__FrameHeader"][::std::mem::align_of::<FLAC__FrameHeader>() - 8usize];
    ["Offset of field: FLAC__FrameHeader::blocksize"]
        [::std::mem::offset_of!(FLAC__FrameHeader, blocksize) - 0usize];
    ["Offset of field: FLAC__FrameHeader::sample_rate"]
        [::std::mem::offset_of!(FLAC__FrameHeader, sample_rate) - 4usize];
    ["Offset of field: FLAC__FrameHeader::channels"]
        [::std::mem::offset_of!(FLAC__FrameHeader, channels) - 8usize];
    ["Offset of field: FLAC__FrameHeader::channel_assignment"]
        [::std::mem::offset_of!(FLAC__FrameHeader, channel_assignment) - 12usize];
    ["Offset of field: FLAC__FrameHeader::bits_per_sample"]
        [::std::mem::offset_of!(FLAC__FrameHeader, bits_per_sample) - 16usize];
    ["Offset of field: FLAC__FrameHeader::number_type"]
        [::std::mem::offset_of!(FLAC__FrameHeader, number_type) - 20usize];
    ["Offset of field: FLAC__FrameHeader::number"]
        [::std::mem::offset_of!(FLAC__FrameHeader, number) - 24usize];
    ["Offset of field: FLAC__FrameHeader::crc"]
        [::std::mem::offset_of!(FLAC__FrameHeader, crc) - 32usize];
};
extern "C" {
    pub static FLAC__FRAME_HEADER_SYNC: u32;
}
extern "C" {
    pub static FLAC__FRAME_HEADER_SYNC_LEN: u32;
}
extern "C" {
    pub static FLAC__FRAME_HEADER_RESERVED_LEN: u32;
}
extern "C" {
    pub static FLAC__FRAME_HEADER_BLOCKING_STRATEGY_LEN: u32;
}
extern "C" {
    pub static FLAC__FRAME_HEADER_BLOCK_SIZE_LEN: u32;
}
extern "C" {
    pub static FLAC__FRAME_HEADER_SAMPLE_RATE_LEN: u32;
}
extern "C" {
    pub static FLAC__FRAME_HEADER_CHANNEL_ASSIGNMENT_LEN: u32;
}
extern "C" {
    pub static FLAC__FRAME_HEADER_BITS_PER_SAMPLE_LEN: u32;
}
extern "C" {
    pub static FLAC__FRAME_HEADER_ZERO_PAD_LEN: u32;
}
extern "C" {
    pub static FLAC__FRAME_HEADER_CRC_LEN: u32;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FLAC__FrameFooter {
    pub crc: FLAC__uint16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FLAC__FrameFooter"][::std::mem::size_of::<FLAC__FrameFooter>() - 2usize];
    ["Alignment of FLAC__FrameFooter"][::std::mem::align_of::<FLAC__FrameFooter>() - 2usize];
    ["Offset of field: FLAC__FrameFooter::crc"]
        [::std::mem::offset_of!(FLAC__FrameFooter, crc) - 0usize];
};
extern "C" {
    pub static FLAC__FRAME_FOOTER_CRC_LEN: u32;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FLAC__Frame {
    pub header: FLAC__FrameHeader,
    pub subframes: [FLAC__Subframe; 8usize],
    pub footer: FLAC__FrameFooter,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FLAC__Frame"][::std::mem::size_of::<FLAC__Frame>() - 3632usize];
    ["Alignment of FLAC__Frame"][::std::mem::align_of::<FLAC__Frame>() - 8usize];
    ["Offset of field: FLAC__Frame::header"][::std::mem::offset_of!(FLAC__Frame, header) - 0usize];
    ["Offset of field: FLAC__Frame::subframes"]
        [::std::mem::offset_of!(FLAC__Frame, subframes) - 40usize];
    ["Offset of field: FLAC__Frame::footer"]
        [::std::mem::offset_of!(FLAC__Frame, footer) - 3624usize];
};
pub const FLAC__MetadataType_FLAC__METADATA_TYPE_STREAMINFO: FLAC__MetadataType = 0;
pub const FLAC__MetadataType_FLAC__METADATA_TYPE_PADDING: FLAC__MetadataType = 1;
pub const FLAC__MetadataType_FLAC__METADATA_TYPE_APPLICATION: FLAC__MetadataType = 2;
pub const FLAC__MetadataType_FLAC__METADATA_TYPE_SEEKTABLE: FLAC__MetadataType = 3;
pub const FLAC__MetadataType_FLAC__METADATA_TYPE_VORBIS_COMMENT: FLAC__MetadataType = 4;
pub const FLAC__MetadataType_FLAC__METADATA_TYPE_CUESHEET: FLAC__MetadataType = 5;
pub const FLAC__MetadataType_FLAC__METADATA_TYPE_PICTURE: FLAC__MetadataType = 6;
pub const FLAC__MetadataType_FLAC__METADATA_TYPE_UNDEFINED: FLAC__MetadataType = 7;
pub const FLAC__MetadataType_FLAC__MAX_METADATA_TYPE: FLAC__MetadataType = 126;
pub type FLAC__MetadataType = ::std::os::raw::c_uint;
extern "C" {
    pub static FLAC__MetadataTypeString: [*const ::std::os::raw::c_char; 0usize];
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FLAC__StreamMetadata_StreamInfo {
    pub min_blocksize: u32,
    pub max_blocksize: u32,
    pub min_framesize: u32,
    pub max_framesize: u32,
    pub sample_rate: u32,
    pub channels: u32,
    pub bits_per_sample: u32,
    pub total_samples: FLAC__uint64,
    pub md5sum: [FLAC__byte; 16usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FLAC__StreamMetadata_StreamInfo"]
        [::std::mem::size_of::<FLAC__StreamMetadata_StreamInfo>() - 56usize];
    ["Alignment of FLAC__StreamMetadata_StreamInfo"]
        [::std::mem::align_of::<FLAC__StreamMetadata_StreamInfo>() - 8usize];
    ["Offset of field: FLAC__StreamMetadata_StreamInfo::min_blocksize"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_StreamInfo, min_blocksize) - 0usize];
    ["Offset of field: FLAC__StreamMetadata_StreamInfo::max_blocksize"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_StreamInfo, max_blocksize) - 4usize];
    ["Offset of field: FLAC__StreamMetadata_StreamInfo::min_framesize"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_StreamInfo, min_framesize) - 8usize];
    ["Offset of field: FLAC__StreamMetadata_StreamInfo::max_framesize"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_StreamInfo, max_framesize) - 12usize];
    ["Offset of field: FLAC__StreamMetadata_StreamInfo::sample_rate"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_StreamInfo, sample_rate) - 16usize];
    ["Offset of field: FLAC__StreamMetadata_StreamInfo::channels"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_StreamInfo, channels) - 20usize];
    ["Offset of field: FLAC__StreamMetadata_StreamInfo::bits_per_sample"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_StreamInfo, bits_per_sample) - 24usize];
    ["Offset of field: FLAC__StreamMetadata_StreamInfo::total_samples"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_StreamInfo, total_samples) - 32usize];
    ["Offset of field: FLAC__StreamMetadata_StreamInfo::md5sum"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_StreamInfo, md5sum) - 40usize];
};
extern "C" {
    pub static FLAC__STREAM_METADATA_STREAMINFO_MIN_BLOCK_SIZE_LEN: u32;
}
extern "C" {
    pub static FLAC__STREAM_METADATA_STREAMINFO_MAX_BLOCK_SIZE_LEN: u32;
}
extern "C" {
    pub static FLAC__STREAM_METADATA_STREAMINFO_MIN_FRAME_SIZE_LEN: u32;
}
extern "C" {
    pub static FLAC__STREAM_METADATA_STREAMINFO_MAX_FRAME_SIZE_LEN: u32;
}
extern "C" {
    pub static FLAC__STREAM_METADATA_STREAMINFO_SAMPLE_RATE_LEN: u32;
}
extern "C" {
    pub static FLAC__STREAM_METADATA_STREAMINFO_CHANNELS_LEN: u32;
}
extern "C" {
    pub static FLAC__STREAM_METADATA_STREAMINFO_BITS_PER_SAMPLE_LEN: u32;
}
extern "C" {
    pub static FLAC__STREAM_METADATA_STREAMINFO_TOTAL_SAMPLES_LEN: u32;
}
extern "C" {
    pub static FLAC__STREAM_METADATA_STREAMINFO_MD5SUM_LEN: u32;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FLAC__StreamMetadata_Padding {
    pub dummy: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FLAC__StreamMetadata_Padding"]
        [::std::mem::size_of::<FLAC__StreamMetadata_Padding>() - 4usize];
    ["Alignment of FLAC__StreamMetadata_Padding"]
        [::std::mem::align_of::<FLAC__StreamMetadata_Padding>() - 4usize];
    ["Offset of field: FLAC__StreamMetadata_Padding::dummy"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_Padding, dummy) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FLAC__StreamMetadata_Application {
    pub id: [FLAC__byte; 4usize],
    pub data: *mut FLAC__byte,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FLAC__StreamMetadata_Application"]
        [::std::mem::size_of::<FLAC__StreamMetadata_Application>() - 16usize];
    ["Alignment of FLAC__StreamMetadata_Application"]
        [::std::mem::align_of::<FLAC__StreamMetadata_Application>() - 8usize];
    ["Offset of field: FLAC__StreamMetadata_Application::id"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_Application, id) - 0usize];
    ["Offset of field: FLAC__StreamMetadata_Application::data"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_Application, data) - 8usize];
};
extern "C" {
    pub static FLAC__STREAM_METADATA_APPLICATION_ID_LEN: u32;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FLAC__StreamMetadata_SeekPoint {
    pub sample_number: FLAC__uint64,
    pub stream_offset: FLAC__uint64,
    pub frame_samples: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FLAC__StreamMetadata_SeekPoint"]
        [::std::mem::size_of::<FLAC__StreamMetadata_SeekPoint>() - 24usize];
    ["Alignment of FLAC__StreamMetadata_SeekPoint"]
        [::std::mem::align_of::<FLAC__StreamMetadata_SeekPoint>() - 8usize];
    ["Offset of field: FLAC__StreamMetadata_SeekPoint::sample_number"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_SeekPoint, sample_number) - 0usize];
    ["Offset of field: FLAC__StreamMetadata_SeekPoint::stream_offset"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_SeekPoint, stream_offset) - 8usize];
    ["Offset of field: FLAC__StreamMetadata_SeekPoint::frame_samples"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_SeekPoint, frame_samples) - 16usize];
};
extern "C" {
    pub static FLAC__STREAM_METADATA_SEEKPOINT_SAMPLE_NUMBER_LEN: u32;
}
extern "C" {
    pub static FLAC__STREAM_METADATA_SEEKPOINT_STREAM_OFFSET_LEN: u32;
}
extern "C" {
    pub static FLAC__STREAM_METADATA_SEEKPOINT_FRAME_SAMPLES_LEN: u32;
}
extern "C" {
    pub static FLAC__STREAM_METADATA_SEEKPOINT_PLACEHOLDER: FLAC__uint64;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FLAC__StreamMetadata_SeekTable {
    pub num_points: u32,
    pub points: *mut FLAC__StreamMetadata_SeekPoint,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FLAC__StreamMetadata_SeekTable"]
        [::std::mem::size_of::<FLAC__StreamMetadata_SeekTable>() - 16usize];
    ["Alignment of FLAC__StreamMetadata_SeekTable"]
        [::std::mem::align_of::<FLAC__StreamMetadata_SeekTable>() - 8usize];
    ["Offset of field: FLAC__StreamMetadata_SeekTable::num_points"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_SeekTable, num_points) - 0usize];
    ["Offset of field: FLAC__StreamMetadata_SeekTable::points"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_SeekTable, points) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FLAC__StreamMetadata_VorbisComment_Entry {
    pub length: FLAC__uint32,
    pub entry: *mut FLAC__byte,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FLAC__StreamMetadata_VorbisComment_Entry"]
        [::std::mem::size_of::<FLAC__StreamMetadata_VorbisComment_Entry>() - 16usize];
    ["Alignment of FLAC__StreamMetadata_VorbisComment_Entry"]
        [::std::mem::align_of::<FLAC__StreamMetadata_VorbisComment_Entry>() - 8usize];
    ["Offset of field: FLAC__StreamMetadata_VorbisComment_Entry::length"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_VorbisComment_Entry, length) - 0usize];
    ["Offset of field: FLAC__StreamMetadata_VorbisComment_Entry::entry"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_VorbisComment_Entry, entry) - 8usize];
};
extern "C" {
    pub static FLAC__STREAM_METADATA_VORBIS_COMMENT_ENTRY_LENGTH_LEN: u32;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FLAC__StreamMetadata_VorbisComment {
    pub vendor_string: FLAC__StreamMetadata_VorbisComment_Entry,
    pub num_comments: FLAC__uint32,
    pub comments: *mut FLAC__StreamMetadata_VorbisComment_Entry,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FLAC__StreamMetadata_VorbisComment"]
        [::std::mem::size_of::<FLAC__StreamMetadata_VorbisComment>() - 32usize];
    ["Alignment of FLAC__StreamMetadata_VorbisComment"]
        [::std::mem::align_of::<FLAC__StreamMetadata_VorbisComment>() - 8usize];
    ["Offset of field: FLAC__StreamMetadata_VorbisComment::vendor_string"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_VorbisComment, vendor_string) - 0usize];
    ["Offset of field: FLAC__StreamMetadata_VorbisComment::num_comments"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_VorbisComment, num_comments) - 16usize];
    ["Offset of field: FLAC__StreamMetadata_VorbisComment::comments"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_VorbisComment, comments) - 24usize];
};
extern "C" {
    pub static FLAC__STREAM_METADATA_VORBIS_COMMENT_NUM_COMMENTS_LEN: u32;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FLAC__StreamMetadata_CueSheet_Index {
    pub offset: FLAC__uint64,
    pub number: FLAC__byte,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FLAC__StreamMetadata_CueSheet_Index"]
        [::std::mem::size_of::<FLAC__StreamMetadata_CueSheet_Index>() - 16usize];
    ["Alignment of FLAC__StreamMetadata_CueSheet_Index"]
        [::std::mem::align_of::<FLAC__StreamMetadata_CueSheet_Index>() - 8usize];
    ["Offset of field: FLAC__StreamMetadata_CueSheet_Index::offset"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_CueSheet_Index, offset) - 0usize];
    ["Offset of field: FLAC__StreamMetadata_CueSheet_Index::number"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_CueSheet_Index, number) - 8usize];
};
extern "C" {
    pub static FLAC__STREAM_METADATA_CUESHEET_INDEX_OFFSET_LEN: u32;
}
extern "C" {
    pub static FLAC__STREAM_METADATA_CUESHEET_INDEX_NUMBER_LEN: u32;
}
extern "C" {
    pub static FLAC__STREAM_METADATA_CUESHEET_INDEX_RESERVED_LEN: u32;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FLAC__StreamMetadata_CueSheet_Track {
    pub offset: FLAC__uint64,
    pub number: FLAC__byte,
    pub isrc: [::std::os::raw::c_char; 13usize],
    pub _bitfield_align_1: [u8; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 1usize]>,
    pub num_indices: FLAC__byte,
    pub indices: *mut FLAC__StreamMetadata_CueSheet_Index,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FLAC__StreamMetadata_CueSheet_Track"]
        [::std::mem::size_of::<FLAC__StreamMetadata_CueSheet_Track>() - 32usize];
    ["Alignment of FLAC__StreamMetadata_CueSheet_Track"]
        [::std::mem::align_of::<FLAC__StreamMetadata_CueSheet_Track>() - 8usize];
    ["Offset of field: FLAC__StreamMetadata_CueSheet_Track::offset"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_CueSheet_Track, offset) - 0usize];
    ["Offset of field: FLAC__StreamMetadata_CueSheet_Track::number"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_CueSheet_Track, number) - 8usize];
    ["Offset of field: FLAC__StreamMetadata_CueSheet_Track::isrc"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_CueSheet_Track, isrc) - 9usize];
    ["Offset of field: FLAC__StreamMetadata_CueSheet_Track::num_indices"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_CueSheet_Track, num_indices) - 23usize];
    ["Offset of field: FLAC__StreamMetadata_CueSheet_Track::indices"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_CueSheet_Track, indices) - 24usize];
};
impl FLAC__StreamMetadata_CueSheet_Track {
    #[inline]
    pub fn type_(&self) -> u32 {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(0usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_type(&mut self, val: u32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(0usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn type__raw(this: *const Self) -> u32 {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 1usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                0usize,
                1u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_type_raw(this: *mut Self, val: u32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 1usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                0usize,
                1u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn pre_emphasis(&self) -> u32 {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(1usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_pre_emphasis(&mut self, val: u32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(1usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn pre_emphasis_raw(this: *const Self) -> u32 {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 1usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                1usize,
                1u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_pre_emphasis_raw(this: *mut Self, val: u32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 1usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                1usize,
                1u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn new_bitfield_1(type_: u32, pre_emphasis: u32) -> __BindgenBitfieldUnit<[u8; 1usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 1usize]> = Default::default();
        __bindgen_bitfield_unit.set(0usize, 1u8, {
            let type_: u32 = unsafe { ::std::mem::transmute(type_) };
            type_ as u64
        });
        __bindgen_bitfield_unit.set(1usize, 1u8, {
            let pre_emphasis: u32 = unsafe { ::std::mem::transmute(pre_emphasis) };
            pre_emphasis as u64
        });
        __bindgen_bitfield_unit
    }
}
extern "C" {
    pub static FLAC__STREAM_METADATA_CUESHEET_TRACK_OFFSET_LEN: u32;
}
extern "C" {
    pub static FLAC__STREAM_METADATA_CUESHEET_TRACK_NUMBER_LEN: u32;
}
extern "C" {
    pub static FLAC__STREAM_METADATA_CUESHEET_TRACK_ISRC_LEN: u32;
}
extern "C" {
    pub static FLAC__STREAM_METADATA_CUESHEET_TRACK_TYPE_LEN: u32;
}
extern "C" {
    pub static FLAC__STREAM_METADATA_CUESHEET_TRACK_PRE_EMPHASIS_LEN: u32;
}
extern "C" {
    pub static FLAC__STREAM_METADATA_CUESHEET_TRACK_RESERVED_LEN: u32;
}
extern "C" {
    pub static FLAC__STREAM_METADATA_CUESHEET_TRACK_NUM_INDICES_LEN: u32;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FLAC__StreamMetadata_CueSheet {
    pub media_catalog_number: [::std::os::raw::c_char; 129usize],
    pub lead_in: FLAC__uint64,
    pub is_cd: FLAC__bool,
    pub num_tracks: u32,
    pub tracks: *mut FLAC__StreamMetadata_CueSheet_Track,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FLAC__StreamMetadata_CueSheet"]
        [::std::mem::size_of::<FLAC__StreamMetadata_CueSheet>() - 160usize];
    ["Alignment of FLAC__StreamMetadata_CueSheet"]
        [::std::mem::align_of::<FLAC__StreamMetadata_CueSheet>() - 8usize];
    ["Offset of field: FLAC__StreamMetadata_CueSheet::media_catalog_number"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_CueSheet, media_catalog_number) - 0usize];
    ["Offset of field: FLAC__StreamMetadata_CueSheet::lead_in"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_CueSheet, lead_in) - 136usize];
    ["Offset of field: FLAC__StreamMetadata_CueSheet::is_cd"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_CueSheet, is_cd) - 144usize];
    ["Offset of field: FLAC__StreamMetadata_CueSheet::num_tracks"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_CueSheet, num_tracks) - 148usize];
    ["Offset of field: FLAC__StreamMetadata_CueSheet::tracks"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_CueSheet, tracks) - 152usize];
};
extern "C" {
    pub static FLAC__STREAM_METADATA_CUESHEET_MEDIA_CATALOG_NUMBER_LEN: u32;
}
extern "C" {
    pub static FLAC__STREAM_METADATA_CUESHEET_LEAD_IN_LEN: u32;
}
extern "C" {
    pub static FLAC__STREAM_METADATA_CUESHEET_IS_CD_LEN: u32;
}
extern "C" {
    pub static FLAC__STREAM_METADATA_CUESHEET_RESERVED_LEN: u32;
}
extern "C" {
    pub static FLAC__STREAM_METADATA_CUESHEET_NUM_TRACKS_LEN: u32;
}
pub const FLAC__StreamMetadata_Picture_Type_FLAC__STREAM_METADATA_PICTURE_TYPE_OTHER:
    FLAC__StreamMetadata_Picture_Type = 0;
pub const FLAC__StreamMetadata_Picture_Type_FLAC__STREAM_METADATA_PICTURE_TYPE_FILE_ICON_STANDARD : FLAC__StreamMetadata_Picture_Type = 1 ;
pub const FLAC__StreamMetadata_Picture_Type_FLAC__STREAM_METADATA_PICTURE_TYPE_FILE_ICON:
    FLAC__StreamMetadata_Picture_Type = 2;
pub const FLAC__StreamMetadata_Picture_Type_FLAC__STREAM_METADATA_PICTURE_TYPE_FRONT_COVER:
    FLAC__StreamMetadata_Picture_Type = 3;
pub const FLAC__StreamMetadata_Picture_Type_FLAC__STREAM_METADATA_PICTURE_TYPE_BACK_COVER:
    FLAC__StreamMetadata_Picture_Type = 4;
pub const FLAC__StreamMetadata_Picture_Type_FLAC__STREAM_METADATA_PICTURE_TYPE_LEAFLET_PAGE:
    FLAC__StreamMetadata_Picture_Type = 5;
pub const FLAC__StreamMetadata_Picture_Type_FLAC__STREAM_METADATA_PICTURE_TYPE_MEDIA:
    FLAC__StreamMetadata_Picture_Type = 6;
pub const FLAC__StreamMetadata_Picture_Type_FLAC__STREAM_METADATA_PICTURE_TYPE_LEAD_ARTIST:
    FLAC__StreamMetadata_Picture_Type = 7;
pub const FLAC__StreamMetadata_Picture_Type_FLAC__STREAM_METADATA_PICTURE_TYPE_ARTIST:
    FLAC__StreamMetadata_Picture_Type = 8;
pub const FLAC__StreamMetadata_Picture_Type_FLAC__STREAM_METADATA_PICTURE_TYPE_CONDUCTOR:
    FLAC__StreamMetadata_Picture_Type = 9;
pub const FLAC__StreamMetadata_Picture_Type_FLAC__STREAM_METADATA_PICTURE_TYPE_BAND:
    FLAC__StreamMetadata_Picture_Type = 10;
pub const FLAC__StreamMetadata_Picture_Type_FLAC__STREAM_METADATA_PICTURE_TYPE_COMPOSER:
    FLAC__StreamMetadata_Picture_Type = 11;
pub const FLAC__StreamMetadata_Picture_Type_FLAC__STREAM_METADATA_PICTURE_TYPE_LYRICIST:
    FLAC__StreamMetadata_Picture_Type = 12;
pub const FLAC__StreamMetadata_Picture_Type_FLAC__STREAM_METADATA_PICTURE_TYPE_RECORDING_LOCATION : FLAC__StreamMetadata_Picture_Type = 13 ;
pub const FLAC__StreamMetadata_Picture_Type_FLAC__STREAM_METADATA_PICTURE_TYPE_DURING_RECORDING:
    FLAC__StreamMetadata_Picture_Type = 14;
pub const FLAC__StreamMetadata_Picture_Type_FLAC__STREAM_METADATA_PICTURE_TYPE_DURING_PERFORMANCE : FLAC__StreamMetadata_Picture_Type = 15 ;
pub const FLAC__StreamMetadata_Picture_Type_FLAC__STREAM_METADATA_PICTURE_TYPE_VIDEO_SCREEN_CAPTURE : FLAC__StreamMetadata_Picture_Type = 16 ;
pub const FLAC__StreamMetadata_Picture_Type_FLAC__STREAM_METADATA_PICTURE_TYPE_FISH:
    FLAC__StreamMetadata_Picture_Type = 17;
pub const FLAC__StreamMetadata_Picture_Type_FLAC__STREAM_METADATA_PICTURE_TYPE_ILLUSTRATION:
    FLAC__StreamMetadata_Picture_Type = 18;
pub const FLAC__StreamMetadata_Picture_Type_FLAC__STREAM_METADATA_PICTURE_TYPE_BAND_LOGOTYPE:
    FLAC__StreamMetadata_Picture_Type = 19;
pub const FLAC__StreamMetadata_Picture_Type_FLAC__STREAM_METADATA_PICTURE_TYPE_PUBLISHER_LOGOTYPE : FLAC__StreamMetadata_Picture_Type = 20 ;
pub const FLAC__StreamMetadata_Picture_Type_FLAC__STREAM_METADATA_PICTURE_TYPE_UNDEFINED:
    FLAC__StreamMetadata_Picture_Type = 21;
pub type FLAC__StreamMetadata_Picture_Type = ::std::os::raw::c_uint;
extern "C" {
    pub static FLAC__StreamMetadata_Picture_TypeString: [*const ::std::os::raw::c_char; 0usize];
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FLAC__StreamMetadata_Picture {
    pub type_: FLAC__StreamMetadata_Picture_Type,
    pub mime_type: *mut ::std::os::raw::c_char,
    pub description: *mut FLAC__byte,
    pub width: FLAC__uint32,
    pub height: FLAC__uint32,
    pub depth: FLAC__uint32,
    pub colors: FLAC__uint32,
    pub data_length: FLAC__uint32,
    pub data: *mut FLAC__byte,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FLAC__StreamMetadata_Picture"]
        [::std::mem::size_of::<FLAC__StreamMetadata_Picture>() - 56usize];
    ["Alignment of FLAC__StreamMetadata_Picture"]
        [::std::mem::align_of::<FLAC__StreamMetadata_Picture>() - 8usize];
    ["Offset of field: FLAC__StreamMetadata_Picture::type_"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_Picture, type_) - 0usize];
    ["Offset of field: FLAC__StreamMetadata_Picture::mime_type"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_Picture, mime_type) - 8usize];
    ["Offset of field: FLAC__StreamMetadata_Picture::description"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_Picture, description) - 16usize];
    ["Offset of field: FLAC__StreamMetadata_Picture::width"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_Picture, width) - 24usize];
    ["Offset of field: FLAC__StreamMetadata_Picture::height"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_Picture, height) - 28usize];
    ["Offset of field: FLAC__StreamMetadata_Picture::depth"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_Picture, depth) - 32usize];
    ["Offset of field: FLAC__StreamMetadata_Picture::colors"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_Picture, colors) - 36usize];
    ["Offset of field: FLAC__StreamMetadata_Picture::data_length"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_Picture, data_length) - 40usize];
    ["Offset of field: FLAC__StreamMetadata_Picture::data"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_Picture, data) - 48usize];
};
extern "C" {
    pub static FLAC__STREAM_METADATA_PICTURE_TYPE_LEN: u32;
}
extern "C" {
    pub static FLAC__STREAM_METADATA_PICTURE_MIME_TYPE_LENGTH_LEN: u32;
}
extern "C" {
    pub static FLAC__STREAM_METADATA_PICTURE_DESCRIPTION_LENGTH_LEN: u32;
}
extern "C" {
    pub static FLAC__STREAM_METADATA_PICTURE_WIDTH_LEN: u32;
}
extern "C" {
    pub static FLAC__STREAM_METADATA_PICTURE_HEIGHT_LEN: u32;
}
extern "C" {
    pub static FLAC__STREAM_METADATA_PICTURE_DEPTH_LEN: u32;
}
extern "C" {
    pub static FLAC__STREAM_METADATA_PICTURE_COLORS_LEN: u32;
}
extern "C" {
    pub static FLAC__STREAM_METADATA_PICTURE_DATA_LENGTH_LEN: u32;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FLAC__StreamMetadata_Unknown {
    pub data: *mut FLAC__byte,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FLAC__StreamMetadata_Unknown"]
        [::std::mem::size_of::<FLAC__StreamMetadata_Unknown>() - 8usize];
    ["Alignment of FLAC__StreamMetadata_Unknown"]
        [::std::mem::align_of::<FLAC__StreamMetadata_Unknown>() - 8usize];
    ["Offset of field: FLAC__StreamMetadata_Unknown::data"]
        [::std::mem::offset_of!(FLAC__StreamMetadata_Unknown, data) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FLAC__StreamMetadata {
    pub type_: FLAC__MetadataType,
    pub is_last: FLAC__bool,
    pub length: u32,
    pub data: FLAC__StreamMetadata__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union FLAC__StreamMetadata__bindgen_ty_1 {
    pub stream_info: FLAC__StreamMetadata_StreamInfo,
    pub padding: FLAC__StreamMetadata_Padding,
    pub application: FLAC__StreamMetadata_Application,
    pub seek_table: FLAC__StreamMetadata_SeekTable,
    pub vorbis_comment: FLAC__StreamMetadata_VorbisComment,
    pub cue_sheet: FLAC__StreamMetadata_CueSheet,
    pub picture: FLAC__StreamMetadata_Picture,
    pub unknown: FLAC__StreamMetadata_Unknown,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FLAC__StreamMetadata__bindgen_ty_1"]
        [::std::mem::size_of::<FLAC__StreamMetadata__bindgen_ty_1>() - 160usize];
    ["Alignment of FLAC__StreamMetadata__bindgen_ty_1"]
        [::std::mem::align_of::<FLAC__StreamMetadata__bindgen_ty_1>() - 8usize];
    ["Offset of field: FLAC__StreamMetadata__bindgen_ty_1::stream_info"]
        [::std::mem::offset_of!(FLAC__StreamMetadata__bindgen_ty_1, stream_info) - 0usize];
    ["Offset of field: FLAC__StreamMetadata__bindgen_ty_1::padding"]
        [::std::mem::offset_of!(FLAC__StreamMetadata__bindgen_ty_1, padding) - 0usize];
    ["Offset of field: FLAC__StreamMetadata__bindgen_ty_1::application"]
        [::std::mem::offset_of!(FLAC__StreamMetadata__bindgen_ty_1, application) - 0usize];
    ["Offset of field: FLAC__StreamMetadata__bindgen_ty_1::seek_table"]
        [::std::mem::offset_of!(FLAC__StreamMetadata__bindgen_ty_1, seek_table) - 0usize];
    ["Offset of field: FLAC__StreamMetadata__bindgen_ty_1::vorbis_comment"]
        [::std::mem::offset_of!(FLAC__StreamMetadata__bindgen_ty_1, vorbis_comment) - 0usize];
    ["Offset of field: FLAC__StreamMetadata__bindgen_ty_1::cue_sheet"]
        [::std::mem::offset_of!(FLAC__StreamMetadata__bindgen_ty_1, cue_sheet) - 0usize];
    ["Offset of field: FLAC__StreamMetadata__bindgen_ty_1::picture"]
        [::std::mem::offset_of!(FLAC__StreamMetadata__bindgen_ty_1, picture) - 0usize];
    ["Offset of field: FLAC__StreamMetadata__bindgen_ty_1::unknown"]
        [::std::mem::offset_of!(FLAC__StreamMetadata__bindgen_ty_1, unknown) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FLAC__StreamMetadata"][::std::mem::size_of::<FLAC__StreamMetadata>() - 176usize];
    ["Alignment of FLAC__StreamMetadata"][::std::mem::align_of::<FLAC__StreamMetadata>() - 8usize];
    ["Offset of field: FLAC__StreamMetadata::type_"]
        [::std::mem::offset_of!(FLAC__StreamMetadata, type_) - 0usize];
    ["Offset of field: FLAC__StreamMetadata::is_last"]
        [::std::mem::offset_of!(FLAC__StreamMetadata, is_last) - 4usize];
    ["Offset of field: FLAC__StreamMetadata::length"]
        [::std::mem::offset_of!(FLAC__StreamMetadata, length) - 8usize];
    ["Offset of field: FLAC__StreamMetadata::data"]
        [::std::mem::offset_of!(FLAC__StreamMetadata, data) - 16usize];
};
extern "C" {
    pub static FLAC__STREAM_METADATA_IS_LAST_LEN: u32;
}
extern "C" {
    pub static FLAC__STREAM_METADATA_TYPE_LEN: u32;
}
extern "C" {
    pub static FLAC__STREAM_METADATA_LENGTH_LEN: u32;
}
extern "C" {
    pub fn FLAC__format_sample_rate_is_valid(sample_rate: u32) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__format_blocksize_is_subset(blocksize: u32, sample_rate: u32) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__format_sample_rate_is_subset(sample_rate: u32) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__format_vorbiscomment_entry_name_is_legal(
        name: *const ::std::os::raw::c_char,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__format_vorbiscomment_entry_value_is_legal(
        value: *const FLAC__byte,
        length: u32,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__format_vorbiscomment_entry_is_legal(
        entry: *const FLAC__byte,
        length: u32,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__format_seektable_is_legal(
        seek_table: *const FLAC__StreamMetadata_SeekTable,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__format_seektable_sort(seek_table: *mut FLAC__StreamMetadata_SeekTable) -> u32;
}
extern "C" {
    pub fn FLAC__format_cuesheet_is_legal(
        cue_sheet: *const FLAC__StreamMetadata_CueSheet,
        check_cd_da_subset: FLAC__bool,
        violation: *mut *const ::std::os::raw::c_char,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__format_picture_is_legal(
        picture: *const FLAC__StreamMetadata_Picture,
        violation: *mut *const ::std::os::raw::c_char,
    ) -> FLAC__bool;
}
pub const FLAC__StreamDecoderState_FLAC__STREAM_DECODER_SEARCH_FOR_METADATA:
    FLAC__StreamDecoderState = 0;
pub const FLAC__StreamDecoderState_FLAC__STREAM_DECODER_READ_METADATA: FLAC__StreamDecoderState = 1;
pub const FLAC__StreamDecoderState_FLAC__STREAM_DECODER_SEARCH_FOR_FRAME_SYNC:
    FLAC__StreamDecoderState = 2;
pub const FLAC__StreamDecoderState_FLAC__STREAM_DECODER_READ_FRAME: FLAC__StreamDecoderState = 3;
pub const FLAC__StreamDecoderState_FLAC__STREAM_DECODER_END_OF_STREAM: FLAC__StreamDecoderState = 4;
pub const FLAC__StreamDecoderState_FLAC__STREAM_DECODER_OGG_ERROR: FLAC__StreamDecoderState = 5;
pub const FLAC__StreamDecoderState_FLAC__STREAM_DECODER_SEEK_ERROR: FLAC__StreamDecoderState = 6;
pub const FLAC__StreamDecoderState_FLAC__STREAM_DECODER_ABORTED: FLAC__StreamDecoderState = 7;
pub const FLAC__StreamDecoderState_FLAC__STREAM_DECODER_MEMORY_ALLOCATION_ERROR:
    FLAC__StreamDecoderState = 8;
pub const FLAC__StreamDecoderState_FLAC__STREAM_DECODER_UNINITIALIZED: FLAC__StreamDecoderState = 9;
pub const FLAC__StreamDecoderState_FLAC__STREAM_DECODER_END_OF_LINK: FLAC__StreamDecoderState = 10;
pub type FLAC__StreamDecoderState = ::std::os::raw::c_uint;
extern "C" {
    pub static FLAC__StreamDecoderStateString: [*const ::std::os::raw::c_char; 0usize];
}
pub const FLAC__StreamDecoderInitStatus_FLAC__STREAM_DECODER_INIT_STATUS_OK:
    FLAC__StreamDecoderInitStatus = 0;
pub const FLAC__StreamDecoderInitStatus_FLAC__STREAM_DECODER_INIT_STATUS_UNSUPPORTED_CONTAINER:
    FLAC__StreamDecoderInitStatus = 1;
pub const FLAC__StreamDecoderInitStatus_FLAC__STREAM_DECODER_INIT_STATUS_INVALID_CALLBACKS:
    FLAC__StreamDecoderInitStatus = 2;
pub const FLAC__StreamDecoderInitStatus_FLAC__STREAM_DECODER_INIT_STATUS_MEMORY_ALLOCATION_ERROR:
    FLAC__StreamDecoderInitStatus = 3;
pub const FLAC__StreamDecoderInitStatus_FLAC__STREAM_DECODER_INIT_STATUS_ERROR_OPENING_FILE:
    FLAC__StreamDecoderInitStatus = 4;
pub const FLAC__StreamDecoderInitStatus_FLAC__STREAM_DECODER_INIT_STATUS_ALREADY_INITIALIZED:
    FLAC__StreamDecoderInitStatus = 5;
pub type FLAC__StreamDecoderInitStatus = ::std::os::raw::c_uint;
extern "C" {
    pub static FLAC__StreamDecoderInitStatusString: [*const ::std::os::raw::c_char; 0usize];
}
pub const FLAC__StreamDecoderReadStatus_FLAC__STREAM_DECODER_READ_STATUS_CONTINUE:
    FLAC__StreamDecoderReadStatus = 0;
pub const FLAC__StreamDecoderReadStatus_FLAC__STREAM_DECODER_READ_STATUS_END_OF_STREAM:
    FLAC__StreamDecoderReadStatus = 1;
pub const FLAC__StreamDecoderReadStatus_FLAC__STREAM_DECODER_READ_STATUS_ABORT:
    FLAC__StreamDecoderReadStatus = 2;
pub const FLAC__StreamDecoderReadStatus_FLAC__STREAM_DECODER_READ_STATUS_END_OF_LINK:
    FLAC__StreamDecoderReadStatus = 3;
pub type FLAC__StreamDecoderReadStatus = ::std::os::raw::c_uint;
extern "C" {
    pub static FLAC__StreamDecoderReadStatusString: [*const ::std::os::raw::c_char; 0usize];
}
pub const FLAC__StreamDecoderSeekStatus_FLAC__STREAM_DECODER_SEEK_STATUS_OK:
    FLAC__StreamDecoderSeekStatus = 0;
pub const FLAC__StreamDecoderSeekStatus_FLAC__STREAM_DECODER_SEEK_STATUS_ERROR:
    FLAC__StreamDecoderSeekStatus = 1;
pub const FLAC__StreamDecoderSeekStatus_FLAC__STREAM_DECODER_SEEK_STATUS_UNSUPPORTED:
    FLAC__StreamDecoderSeekStatus = 2;
pub type FLAC__StreamDecoderSeekStatus = ::std::os::raw::c_uint;
extern "C" {
    pub static FLAC__StreamDecoderSeekStatusString: [*const ::std::os::raw::c_char; 0usize];
}
pub const FLAC__StreamDecoderTellStatus_FLAC__STREAM_DECODER_TELL_STATUS_OK:
    FLAC__StreamDecoderTellStatus = 0;
pub const FLAC__StreamDecoderTellStatus_FLAC__STREAM_DECODER_TELL_STATUS_ERROR:
    FLAC__StreamDecoderTellStatus = 1;
pub const FLAC__StreamDecoderTellStatus_FLAC__STREAM_DECODER_TELL_STATUS_UNSUPPORTED:
    FLAC__StreamDecoderTellStatus = 2;
pub type FLAC__StreamDecoderTellStatus = ::std::os::raw::c_uint;
extern "C" {
    pub static FLAC__StreamDecoderTellStatusString: [*const ::std::os::raw::c_char; 0usize];
}
pub const FLAC__StreamDecoderLengthStatus_FLAC__STREAM_DECODER_LENGTH_STATUS_OK:
    FLAC__StreamDecoderLengthStatus = 0;
pub const FLAC__StreamDecoderLengthStatus_FLAC__STREAM_DECODER_LENGTH_STATUS_ERROR:
    FLAC__StreamDecoderLengthStatus = 1;
pub const FLAC__StreamDecoderLengthStatus_FLAC__STREAM_DECODER_LENGTH_STATUS_UNSUPPORTED:
    FLAC__StreamDecoderLengthStatus = 2;
pub type FLAC__StreamDecoderLengthStatus = ::std::os::raw::c_uint;
extern "C" {
    pub static FLAC__StreamDecoderLengthStatusString: [*const ::std::os::raw::c_char; 0usize];
}
pub const FLAC__StreamDecoderWriteStatus_FLAC__STREAM_DECODER_WRITE_STATUS_CONTINUE:
    FLAC__StreamDecoderWriteStatus = 0;
pub const FLAC__StreamDecoderWriteStatus_FLAC__STREAM_DECODER_WRITE_STATUS_ABORT:
    FLAC__StreamDecoderWriteStatus = 1;
pub type FLAC__StreamDecoderWriteStatus = ::std::os::raw::c_uint;
extern "C" {
    pub static FLAC__StreamDecoderWriteStatusString: [*const ::std::os::raw::c_char; 0usize];
}
pub const FLAC__StreamDecoderErrorStatus_FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC:
    FLAC__StreamDecoderErrorStatus = 0;
pub const FLAC__StreamDecoderErrorStatus_FLAC__STREAM_DECODER_ERROR_STATUS_BAD_HEADER:
    FLAC__StreamDecoderErrorStatus = 1;
pub const FLAC__StreamDecoderErrorStatus_FLAC__STREAM_DECODER_ERROR_STATUS_FRAME_CRC_MISMATCH:
    FLAC__StreamDecoderErrorStatus = 2;
pub const FLAC__StreamDecoderErrorStatus_FLAC__STREAM_DECODER_ERROR_STATUS_UNPARSEABLE_STREAM:
    FLAC__StreamDecoderErrorStatus = 3;
pub const FLAC__StreamDecoderErrorStatus_FLAC__STREAM_DECODER_ERROR_STATUS_BAD_METADATA:
    FLAC__StreamDecoderErrorStatus = 4;
pub const FLAC__StreamDecoderErrorStatus_FLAC__STREAM_DECODER_ERROR_STATUS_OUT_OF_BOUNDS:
    FLAC__StreamDecoderErrorStatus = 5;
pub const FLAC__StreamDecoderErrorStatus_FLAC__STREAM_DECODER_ERROR_STATUS_MISSING_FRAME:
    FLAC__StreamDecoderErrorStatus = 6;
pub type FLAC__StreamDecoderErrorStatus = ::std::os::raw::c_uint;
extern "C" {
    pub static FLAC__StreamDecoderErrorStatusString: [*const ::std::os::raw::c_char; 0usize];
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FLAC__StreamDecoderProtected {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FLAC__StreamDecoderPrivate {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FLAC__StreamDecoder {
    pub protected_: *mut FLAC__StreamDecoderProtected,
    pub private_: *mut FLAC__StreamDecoderPrivate,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FLAC__StreamDecoder"][::std::mem::size_of::<FLAC__StreamDecoder>() - 16usize];
    ["Alignment of FLAC__StreamDecoder"][::std::mem::align_of::<FLAC__StreamDecoder>() - 8usize];
    ["Offset of field: FLAC__StreamDecoder::protected_"]
        [::std::mem::offset_of!(FLAC__StreamDecoder, protected_) - 0usize];
    ["Offset of field: FLAC__StreamDecoder::private_"]
        [::std::mem::offset_of!(FLAC__StreamDecoder, private_) - 8usize];
};
pub type FLAC__StreamDecoderReadCallback = ::std::option::Option<
    unsafe extern "C" fn(
        decoder: *const FLAC__StreamDecoder,
        buffer: *mut FLAC__byte,
        bytes: *mut usize,
        client_data: *mut ::std::os::raw::c_void,
    ) -> FLAC__StreamDecoderReadStatus,
>;
pub type FLAC__StreamDecoderSeekCallback = ::std::option::Option<
    unsafe extern "C" fn(
        decoder: *const FLAC__StreamDecoder,
        absolute_byte_offset: FLAC__uint64,
        client_data: *mut ::std::os::raw::c_void,
    ) -> FLAC__StreamDecoderSeekStatus,
>;
pub type FLAC__StreamDecoderTellCallback = ::std::option::Option<
    unsafe extern "C" fn(
        decoder: *const FLAC__StreamDecoder,
        absolute_byte_offset: *mut FLAC__uint64,
        client_data: *mut ::std::os::raw::c_void,
    ) -> FLAC__StreamDecoderTellStatus,
>;
pub type FLAC__StreamDecoderLengthCallback = ::std::option::Option<
    unsafe extern "C" fn(
        decoder: *const FLAC__StreamDecoder,
        stream_length: *mut FLAC__uint64,
        client_data: *mut ::std::os::raw::c_void,
    ) -> FLAC__StreamDecoderLengthStatus,
>;
pub type FLAC__StreamDecoderEofCallback = ::std::option::Option<
    unsafe extern "C" fn(
        decoder: *const FLAC__StreamDecoder,
        client_data: *mut ::std::os::raw::c_void,
    ) -> FLAC__bool,
>;
pub type FLAC__StreamDecoderWriteCallback = ::std::option::Option<
    unsafe extern "C" fn(
        decoder: *const FLAC__StreamDecoder,
        frame: *const FLAC__Frame,
        buffer: *const *const FLAC__int32,
        client_data: *mut ::std::os::raw::c_void,
    ) -> FLAC__StreamDecoderWriteStatus,
>;
pub type FLAC__StreamDecoderMetadataCallback = ::std::option::Option<
    unsafe extern "C" fn(
        decoder: *const FLAC__StreamDecoder,
        metadata: *const FLAC__StreamMetadata,
        client_data: *mut ::std::os::raw::c_void,
    ),
>;
pub type FLAC__StreamDecoderErrorCallback = ::std::option::Option<
    unsafe extern "C" fn(
        decoder: *const FLAC__StreamDecoder,
        status: FLAC__StreamDecoderErrorStatus,
        client_data: *mut ::std::os::raw::c_void,
    ),
>;
extern "C" {
    pub fn FLAC__stream_decoder_new() -> *mut FLAC__StreamDecoder;
}
extern "C" {
    pub fn FLAC__stream_decoder_delete(decoder: *mut FLAC__StreamDecoder);
}
extern "C" {
    pub fn FLAC__stream_decoder_set_ogg_serial_number(
        decoder: *mut FLAC__StreamDecoder,
        serial_number: ::std::os::raw::c_long,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_decoder_set_decode_chained_stream(
        decoder: *mut FLAC__StreamDecoder,
        value: FLAC__bool,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_decoder_set_md5_checking(
        decoder: *mut FLAC__StreamDecoder,
        value: FLAC__bool,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_decoder_set_metadata_respond(
        decoder: *mut FLAC__StreamDecoder,
        type_: FLAC__MetadataType,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_decoder_set_metadata_respond_application(
        decoder: *mut FLAC__StreamDecoder,
        id: *const FLAC__byte,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_decoder_set_metadata_respond_all(
        decoder: *mut FLAC__StreamDecoder,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_decoder_set_metadata_ignore(
        decoder: *mut FLAC__StreamDecoder,
        type_: FLAC__MetadataType,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_decoder_set_metadata_ignore_application(
        decoder: *mut FLAC__StreamDecoder,
        id: *const FLAC__byte,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_decoder_set_metadata_ignore_all(
        decoder: *mut FLAC__StreamDecoder,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_decoder_get_state(
        decoder: *const FLAC__StreamDecoder,
    ) -> FLAC__StreamDecoderState;
}
extern "C" {
    pub fn FLAC__stream_decoder_get_resolved_state_string(
        decoder: *const FLAC__StreamDecoder,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn FLAC__stream_decoder_get_decode_chained_stream(
        decoder: *const FLAC__StreamDecoder,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_decoder_get_md5_checking(decoder: *const FLAC__StreamDecoder)
        -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_decoder_get_total_samples(
        decoder: *const FLAC__StreamDecoder,
    ) -> FLAC__uint64;
}
extern "C" {
    pub fn FLAC__stream_decoder_find_total_samples(
        decoder: *mut FLAC__StreamDecoder,
    ) -> FLAC__uint64;
}
extern "C" {
    pub fn FLAC__stream_decoder_get_channels(decoder: *const FLAC__StreamDecoder) -> u32;
}
extern "C" {
    pub fn FLAC__stream_decoder_get_channel_assignment(
        decoder: *const FLAC__StreamDecoder,
    ) -> FLAC__ChannelAssignment;
}
extern "C" {
    pub fn FLAC__stream_decoder_get_bits_per_sample(decoder: *const FLAC__StreamDecoder) -> u32;
}
extern "C" {
    pub fn FLAC__stream_decoder_get_sample_rate(decoder: *const FLAC__StreamDecoder) -> u32;
}
extern "C" {
    pub fn FLAC__stream_decoder_get_blocksize(decoder: *const FLAC__StreamDecoder) -> u32;
}
extern "C" {
    pub fn FLAC__stream_decoder_get_decode_position(
        decoder: *const FLAC__StreamDecoder,
        position: *mut FLAC__uint64,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_decoder_get_client_data(
        decoder: *mut FLAC__StreamDecoder,
    ) -> *const ::std::os::raw::c_void;
}
extern "C" {
    pub fn FLAC__stream_decoder_get_link_lengths(
        decoder: *mut FLAC__StreamDecoder,
        link_lengths: *mut *mut FLAC__uint64,
    ) -> i32;
}
extern "C" {
    pub fn FLAC__stream_decoder_init_stream(
        decoder: *mut FLAC__StreamDecoder,
        read_callback: FLAC__StreamDecoderReadCallback,
        seek_callback: FLAC__StreamDecoderSeekCallback,
        tell_callback: FLAC__StreamDecoderTellCallback,
        length_callback: FLAC__StreamDecoderLengthCallback,
        eof_callback: FLAC__StreamDecoderEofCallback,
        write_callback: FLAC__StreamDecoderWriteCallback,
        metadata_callback: FLAC__StreamDecoderMetadataCallback,
        error_callback: FLAC__StreamDecoderErrorCallback,
        client_data: *mut ::std::os::raw::c_void,
    ) -> FLAC__StreamDecoderInitStatus;
}
extern "C" {
    pub fn FLAC__stream_decoder_init_ogg_stream(
        decoder: *mut FLAC__StreamDecoder,
        read_callback: FLAC__StreamDecoderReadCallback,
        seek_callback: FLAC__StreamDecoderSeekCallback,
        tell_callback: FLAC__StreamDecoderTellCallback,
        length_callback: FLAC__StreamDecoderLengthCallback,
        eof_callback: FLAC__StreamDecoderEofCallback,
        write_callback: FLAC__StreamDecoderWriteCallback,
        metadata_callback: FLAC__StreamDecoderMetadataCallback,
        error_callback: FLAC__StreamDecoderErrorCallback,
        client_data: *mut ::std::os::raw::c_void,
    ) -> FLAC__StreamDecoderInitStatus;
}
extern "C" {
    pub fn FLAC__stream_decoder_init_file(
        decoder: *mut FLAC__StreamDecoder,
        filename: *const ::std::os::raw::c_char,
        write_callback: FLAC__StreamDecoderWriteCallback,
        metadata_callback: FLAC__StreamDecoderMetadataCallback,
        error_callback: FLAC__StreamDecoderErrorCallback,
        client_data: *mut ::std::os::raw::c_void,
    ) -> FLAC__StreamDecoderInitStatus;
}
extern "C" {
    pub fn FLAC__stream_decoder_init_ogg_file(
        decoder: *mut FLAC__StreamDecoder,
        filename: *const ::std::os::raw::c_char,
        write_callback: FLAC__StreamDecoderWriteCallback,
        metadata_callback: FLAC__StreamDecoderMetadataCallback,
        error_callback: FLAC__StreamDecoderErrorCallback,
        client_data: *mut ::std::os::raw::c_void,
    ) -> FLAC__StreamDecoderInitStatus;
}
extern "C" {
    pub fn FLAC__stream_decoder_finish(decoder: *mut FLAC__StreamDecoder) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_decoder_finish_link(decoder: *mut FLAC__StreamDecoder) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_decoder_flush(decoder: *mut FLAC__StreamDecoder) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_decoder_reset(decoder: *mut FLAC__StreamDecoder) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_decoder_process_single(decoder: *mut FLAC__StreamDecoder) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_decoder_process_until_end_of_metadata(
        decoder: *mut FLAC__StreamDecoder,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_decoder_process_until_end_of_link(
        decoder: *mut FLAC__StreamDecoder,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_decoder_process_until_end_of_stream(
        decoder: *mut FLAC__StreamDecoder,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_decoder_skip_single_frame(decoder: *mut FLAC__StreamDecoder) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_decoder_skip_single_link(decoder: *mut FLAC__StreamDecoder) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_decoder_seek_absolute(
        decoder: *mut FLAC__StreamDecoder,
        sample: FLAC__uint64,
    ) -> FLAC__bool;
}
pub const FLAC__StreamEncoderState_FLAC__STREAM_ENCODER_OK: FLAC__StreamEncoderState = 0;
pub const FLAC__StreamEncoderState_FLAC__STREAM_ENCODER_UNINITIALIZED: FLAC__StreamEncoderState = 1;
pub const FLAC__StreamEncoderState_FLAC__STREAM_ENCODER_OGG_ERROR: FLAC__StreamEncoderState = 2;
pub const FLAC__StreamEncoderState_FLAC__STREAM_ENCODER_VERIFY_DECODER_ERROR:
    FLAC__StreamEncoderState = 3;
pub const FLAC__StreamEncoderState_FLAC__STREAM_ENCODER_VERIFY_MISMATCH_IN_AUDIO_DATA:
    FLAC__StreamEncoderState = 4;
pub const FLAC__StreamEncoderState_FLAC__STREAM_ENCODER_CLIENT_ERROR: FLAC__StreamEncoderState = 5;
pub const FLAC__StreamEncoderState_FLAC__STREAM_ENCODER_IO_ERROR: FLAC__StreamEncoderState = 6;
pub const FLAC__StreamEncoderState_FLAC__STREAM_ENCODER_FRAMING_ERROR: FLAC__StreamEncoderState = 7;
pub const FLAC__StreamEncoderState_FLAC__STREAM_ENCODER_MEMORY_ALLOCATION_ERROR:
    FLAC__StreamEncoderState = 8;
pub type FLAC__StreamEncoderState = ::std::os::raw::c_uint;
extern "C" {
    pub static FLAC__StreamEncoderStateString: [*const ::std::os::raw::c_char; 0usize];
}
pub const FLAC__StreamEncoderInitStatus_FLAC__STREAM_ENCODER_INIT_STATUS_OK:
    FLAC__StreamEncoderInitStatus = 0;
pub const FLAC__StreamEncoderInitStatus_FLAC__STREAM_ENCODER_INIT_STATUS_ENCODER_ERROR:
    FLAC__StreamEncoderInitStatus = 1;
pub const FLAC__StreamEncoderInitStatus_FLAC__STREAM_ENCODER_INIT_STATUS_UNSUPPORTED_CONTAINER:
    FLAC__StreamEncoderInitStatus = 2;
pub const FLAC__StreamEncoderInitStatus_FLAC__STREAM_ENCODER_INIT_STATUS_INVALID_CALLBACKS:
    FLAC__StreamEncoderInitStatus = 3;
pub const FLAC__StreamEncoderInitStatus_FLAC__STREAM_ENCODER_INIT_STATUS_INVALID_NUMBER_OF_CHANNELS : FLAC__StreamEncoderInitStatus = 4 ;
pub const FLAC__StreamEncoderInitStatus_FLAC__STREAM_ENCODER_INIT_STATUS_INVALID_BITS_PER_SAMPLE:
    FLAC__StreamEncoderInitStatus = 5;
pub const FLAC__StreamEncoderInitStatus_FLAC__STREAM_ENCODER_INIT_STATUS_INVALID_SAMPLE_RATE:
    FLAC__StreamEncoderInitStatus = 6;
pub const FLAC__StreamEncoderInitStatus_FLAC__STREAM_ENCODER_INIT_STATUS_INVALID_BLOCK_SIZE:
    FLAC__StreamEncoderInitStatus = 7;
pub const FLAC__StreamEncoderInitStatus_FLAC__STREAM_ENCODER_INIT_STATUS_INVALID_MAX_LPC_ORDER:
    FLAC__StreamEncoderInitStatus = 8;
pub const FLAC__StreamEncoderInitStatus_FLAC__STREAM_ENCODER_INIT_STATUS_INVALID_QLP_COEFF_PRECISION : FLAC__StreamEncoderInitStatus = 9 ;
pub const FLAC__StreamEncoderInitStatus_FLAC__STREAM_ENCODER_INIT_STATUS_BLOCK_SIZE_TOO_SMALL_FOR_LPC_ORDER : FLAC__StreamEncoderInitStatus = 10 ;
pub const FLAC__StreamEncoderInitStatus_FLAC__STREAM_ENCODER_INIT_STATUS_NOT_STREAMABLE:
    FLAC__StreamEncoderInitStatus = 11;
pub const FLAC__StreamEncoderInitStatus_FLAC__STREAM_ENCODER_INIT_STATUS_INVALID_METADATA:
    FLAC__StreamEncoderInitStatus = 12;
pub const FLAC__StreamEncoderInitStatus_FLAC__STREAM_ENCODER_INIT_STATUS_ALREADY_INITIALIZED:
    FLAC__StreamEncoderInitStatus = 13;
pub type FLAC__StreamEncoderInitStatus = ::std::os::raw::c_uint;
extern "C" {
    pub static FLAC__StreamEncoderInitStatusString: [*const ::std::os::raw::c_char; 0usize];
}
pub const FLAC__StreamEncoderReadStatus_FLAC__STREAM_ENCODER_READ_STATUS_CONTINUE:
    FLAC__StreamEncoderReadStatus = 0;
pub const FLAC__StreamEncoderReadStatus_FLAC__STREAM_ENCODER_READ_STATUS_END_OF_STREAM:
    FLAC__StreamEncoderReadStatus = 1;
pub const FLAC__StreamEncoderReadStatus_FLAC__STREAM_ENCODER_READ_STATUS_ABORT:
    FLAC__StreamEncoderReadStatus = 2;
pub const FLAC__StreamEncoderReadStatus_FLAC__STREAM_ENCODER_READ_STATUS_UNSUPPORTED:
    FLAC__StreamEncoderReadStatus = 3;
pub type FLAC__StreamEncoderReadStatus = ::std::os::raw::c_uint;
extern "C" {
    pub static FLAC__StreamEncoderReadStatusString: [*const ::std::os::raw::c_char; 0usize];
}
pub const FLAC__StreamEncoderWriteStatus_FLAC__STREAM_ENCODER_WRITE_STATUS_OK:
    FLAC__StreamEncoderWriteStatus = 0;
pub const FLAC__StreamEncoderWriteStatus_FLAC__STREAM_ENCODER_WRITE_STATUS_FATAL_ERROR:
    FLAC__StreamEncoderWriteStatus = 1;
pub type FLAC__StreamEncoderWriteStatus = ::std::os::raw::c_uint;
extern "C" {
    pub static FLAC__StreamEncoderWriteStatusString: [*const ::std::os::raw::c_char; 0usize];
}
pub const FLAC__StreamEncoderSeekStatus_FLAC__STREAM_ENCODER_SEEK_STATUS_OK:
    FLAC__StreamEncoderSeekStatus = 0;
pub const FLAC__StreamEncoderSeekStatus_FLAC__STREAM_ENCODER_SEEK_STATUS_ERROR:
    FLAC__StreamEncoderSeekStatus = 1;
pub const FLAC__StreamEncoderSeekStatus_FLAC__STREAM_ENCODER_SEEK_STATUS_UNSUPPORTED:
    FLAC__StreamEncoderSeekStatus = 2;
pub type FLAC__StreamEncoderSeekStatus = ::std::os::raw::c_uint;
extern "C" {
    pub static FLAC__StreamEncoderSeekStatusString: [*const ::std::os::raw::c_char; 0usize];
}
pub const FLAC__StreamEncoderTellStatus_FLAC__STREAM_ENCODER_TELL_STATUS_OK:
    FLAC__StreamEncoderTellStatus = 0;
pub const FLAC__StreamEncoderTellStatus_FLAC__STREAM_ENCODER_TELL_STATUS_ERROR:
    FLAC__StreamEncoderTellStatus = 1;
pub const FLAC__StreamEncoderTellStatus_FLAC__STREAM_ENCODER_TELL_STATUS_UNSUPPORTED:
    FLAC__StreamEncoderTellStatus = 2;
pub type FLAC__StreamEncoderTellStatus = ::std::os::raw::c_uint;
extern "C" {
    pub static FLAC__StreamEncoderTellStatusString: [*const ::std::os::raw::c_char; 0usize];
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FLAC__StreamEncoderProtected {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FLAC__StreamEncoderPrivate {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FLAC__StreamEncoder {
    pub protected_: *mut FLAC__StreamEncoderProtected,
    pub private_: *mut FLAC__StreamEncoderPrivate,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FLAC__StreamEncoder"][::std::mem::size_of::<FLAC__StreamEncoder>() - 16usize];
    ["Alignment of FLAC__StreamEncoder"][::std::mem::align_of::<FLAC__StreamEncoder>() - 8usize];
    ["Offset of field: FLAC__StreamEncoder::protected_"]
        [::std::mem::offset_of!(FLAC__StreamEncoder, protected_) - 0usize];
    ["Offset of field: FLAC__StreamEncoder::private_"]
        [::std::mem::offset_of!(FLAC__StreamEncoder, private_) - 8usize];
};
pub type FLAC__StreamEncoderReadCallback = ::std::option::Option<
    unsafe extern "C" fn(
        encoder: *const FLAC__StreamEncoder,
        buffer: *mut FLAC__byte,
        bytes: *mut usize,
        client_data: *mut ::std::os::raw::c_void,
    ) -> FLAC__StreamEncoderReadStatus,
>;
pub type FLAC__StreamEncoderWriteCallback = ::std::option::Option<
    unsafe extern "C" fn(
        encoder: *const FLAC__StreamEncoder,
        buffer: *const FLAC__byte,
        bytes: usize,
        samples: u32,
        current_frame: u32,
        client_data: *mut ::std::os::raw::c_void,
    ) -> FLAC__StreamEncoderWriteStatus,
>;
pub type FLAC__StreamEncoderSeekCallback = ::std::option::Option<
    unsafe extern "C" fn(
        encoder: *const FLAC__StreamEncoder,
        absolute_byte_offset: FLAC__uint64,
        client_data: *mut ::std::os::raw::c_void,
    ) -> FLAC__StreamEncoderSeekStatus,
>;
pub type FLAC__StreamEncoderTellCallback = ::std::option::Option<
    unsafe extern "C" fn(
        encoder: *const FLAC__StreamEncoder,
        absolute_byte_offset: *mut FLAC__uint64,
        client_data: *mut ::std::os::raw::c_void,
    ) -> FLAC__StreamEncoderTellStatus,
>;
pub type FLAC__StreamEncoderMetadataCallback = ::std::option::Option<
    unsafe extern "C" fn(
        encoder: *const FLAC__StreamEncoder,
        metadata: *const FLAC__StreamMetadata,
        client_data: *mut ::std::os::raw::c_void,
    ),
>;
pub type FLAC__StreamEncoderProgressCallback = ::std::option::Option<
    unsafe extern "C" fn(
        encoder: *const FLAC__StreamEncoder,
        bytes_written: FLAC__uint64,
        samples_written: FLAC__uint64,
        frames_written: u32,
        total_frames_estimate: u32,
        client_data: *mut ::std::os::raw::c_void,
    ),
>;
extern "C" {
    pub fn FLAC__stream_encoder_new() -> *mut FLAC__StreamEncoder;
}
extern "C" {
    pub fn FLAC__stream_encoder_delete(encoder: *mut FLAC__StreamEncoder);
}
extern "C" {
    pub fn FLAC__stream_encoder_set_ogg_serial_number(
        encoder: *mut FLAC__StreamEncoder,
        serial_number: ::std::os::raw::c_long,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_encoder_set_verify(
        encoder: *mut FLAC__StreamEncoder,
        value: FLAC__bool,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_encoder_set_streamable_subset(
        encoder: *mut FLAC__StreamEncoder,
        value: FLAC__bool,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_encoder_set_channels(
        encoder: *mut FLAC__StreamEncoder,
        value: u32,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_encoder_set_bits_per_sample(
        encoder: *mut FLAC__StreamEncoder,
        value: u32,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_encoder_set_sample_rate(
        encoder: *mut FLAC__StreamEncoder,
        value: u32,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_encoder_set_compression_level(
        encoder: *mut FLAC__StreamEncoder,
        value: u32,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_encoder_set_blocksize(
        encoder: *mut FLAC__StreamEncoder,
        value: u32,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_encoder_set_do_mid_side_stereo(
        encoder: *mut FLAC__StreamEncoder,
        value: FLAC__bool,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_encoder_set_loose_mid_side_stereo(
        encoder: *mut FLAC__StreamEncoder,
        value: FLAC__bool,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_encoder_set_apodization(
        encoder: *mut FLAC__StreamEncoder,
        specification: *const ::std::os::raw::c_char,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_encoder_set_max_lpc_order(
        encoder: *mut FLAC__StreamEncoder,
        value: u32,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_encoder_set_qlp_coeff_precision(
        encoder: *mut FLAC__StreamEncoder,
        value: u32,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_encoder_set_do_qlp_coeff_prec_search(
        encoder: *mut FLAC__StreamEncoder,
        value: FLAC__bool,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_encoder_set_do_escape_coding(
        encoder: *mut FLAC__StreamEncoder,
        value: FLAC__bool,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_encoder_set_do_exhaustive_model_search(
        encoder: *mut FLAC__StreamEncoder,
        value: FLAC__bool,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_encoder_set_min_residual_partition_order(
        encoder: *mut FLAC__StreamEncoder,
        value: u32,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_encoder_set_max_residual_partition_order(
        encoder: *mut FLAC__StreamEncoder,
        value: u32,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_encoder_set_num_threads(
        encoder: *mut FLAC__StreamEncoder,
        value: u32,
    ) -> u32;
}
extern "C" {
    pub fn FLAC__stream_encoder_set_rice_parameter_search_dist(
        encoder: *mut FLAC__StreamEncoder,
        value: u32,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_encoder_set_total_samples_estimate(
        encoder: *mut FLAC__StreamEncoder,
        value: FLAC__uint64,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_encoder_set_metadata(
        encoder: *mut FLAC__StreamEncoder,
        metadata: *mut *mut FLAC__StreamMetadata,
        num_blocks: u32,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_encoder_set_limit_min_bitrate(
        encoder: *mut FLAC__StreamEncoder,
        value: FLAC__bool,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_encoder_get_state(
        encoder: *const FLAC__StreamEncoder,
    ) -> FLAC__StreamEncoderState;
}
extern "C" {
    pub fn FLAC__stream_encoder_get_verify_decoder_state(
        encoder: *const FLAC__StreamEncoder,
    ) -> FLAC__StreamDecoderState;
}
extern "C" {
    pub fn FLAC__stream_encoder_get_resolved_state_string(
        encoder: *const FLAC__StreamEncoder,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn FLAC__stream_encoder_get_verify_decoder_error_stats(
        encoder: *const FLAC__StreamEncoder,
        absolute_sample: *mut FLAC__uint64,
        frame_number: *mut u32,
        channel: *mut u32,
        sample: *mut u32,
        expected: *mut FLAC__int32,
        got: *mut FLAC__int32,
    );
}
extern "C" {
    pub fn FLAC__stream_encoder_get_verify(encoder: *const FLAC__StreamEncoder) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_encoder_get_streamable_subset(
        encoder: *const FLAC__StreamEncoder,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_encoder_get_channels(encoder: *const FLAC__StreamEncoder) -> u32;
}
extern "C" {
    pub fn FLAC__stream_encoder_get_bits_per_sample(encoder: *const FLAC__StreamEncoder) -> u32;
}
extern "C" {
    pub fn FLAC__stream_encoder_get_sample_rate(encoder: *const FLAC__StreamEncoder) -> u32;
}
extern "C" {
    pub fn FLAC__stream_encoder_get_blocksize(encoder: *const FLAC__StreamEncoder) -> u32;
}
extern "C" {
    pub fn FLAC__stream_encoder_get_do_mid_side_stereo(
        encoder: *const FLAC__StreamEncoder,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_encoder_get_loose_mid_side_stereo(
        encoder: *const FLAC__StreamEncoder,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_encoder_get_max_lpc_order(encoder: *const FLAC__StreamEncoder) -> u32;
}
extern "C" {
    pub fn FLAC__stream_encoder_get_qlp_coeff_precision(encoder: *const FLAC__StreamEncoder)
        -> u32;
}
extern "C" {
    pub fn FLAC__stream_encoder_get_do_qlp_coeff_prec_search(
        encoder: *const FLAC__StreamEncoder,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_encoder_get_do_escape_coding(
        encoder: *const FLAC__StreamEncoder,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_encoder_get_do_exhaustive_model_search(
        encoder: *const FLAC__StreamEncoder,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_encoder_get_min_residual_partition_order(
        encoder: *const FLAC__StreamEncoder,
    ) -> u32;
}
extern "C" {
    pub fn FLAC__stream_encoder_get_max_residual_partition_order(
        encoder: *const FLAC__StreamEncoder,
    ) -> u32;
}
extern "C" {
    pub fn FLAC__stream_encoder_get_num_threads(encoder: *const FLAC__StreamEncoder) -> u32;
}
extern "C" {
    pub fn FLAC__stream_encoder_get_rice_parameter_search_dist(
        encoder: *const FLAC__StreamEncoder,
    ) -> u32;
}
extern "C" {
    pub fn FLAC__stream_encoder_get_total_samples_estimate(
        encoder: *const FLAC__StreamEncoder,
    ) -> FLAC__uint64;
}
extern "C" {
    pub fn FLAC__stream_encoder_get_limit_min_bitrate(
        encoder: *const FLAC__StreamEncoder,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_encoder_init_stream(
        encoder: *mut FLAC__StreamEncoder,
        write_callback: FLAC__StreamEncoderWriteCallback,
        seek_callback: FLAC__StreamEncoderSeekCallback,
        tell_callback: FLAC__StreamEncoderTellCallback,
        metadata_callback: FLAC__StreamEncoderMetadataCallback,
        client_data: *mut ::std::os::raw::c_void,
    ) -> FLAC__StreamEncoderInitStatus;
}
extern "C" {
    pub fn FLAC__stream_encoder_init_ogg_stream(
        encoder: *mut FLAC__StreamEncoder,
        read_callback: FLAC__StreamEncoderReadCallback,
        write_callback: FLAC__StreamEncoderWriteCallback,
        seek_callback: FLAC__StreamEncoderSeekCallback,
        tell_callback: FLAC__StreamEncoderTellCallback,
        metadata_callback: FLAC__StreamEncoderMetadataCallback,
        client_data: *mut ::std::os::raw::c_void,
    ) -> FLAC__StreamEncoderInitStatus;
}
extern "C" {
    pub fn FLAC__stream_encoder_init_file(
        encoder: *mut FLAC__StreamEncoder,
        filename: *const ::std::os::raw::c_char,
        progress_callback: FLAC__StreamEncoderProgressCallback,
        client_data: *mut ::std::os::raw::c_void,
    ) -> FLAC__StreamEncoderInitStatus;
}
extern "C" {
    pub fn FLAC__stream_encoder_init_ogg_file(
        encoder: *mut FLAC__StreamEncoder,
        filename: *const ::std::os::raw::c_char,
        progress_callback: FLAC__StreamEncoderProgressCallback,
        client_data: *mut ::std::os::raw::c_void,
    ) -> FLAC__StreamEncoderInitStatus;
}
extern "C" {
    pub fn FLAC__stream_encoder_finish(encoder: *mut FLAC__StreamEncoder) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_encoder_process(
        encoder: *mut FLAC__StreamEncoder,
        buffer: *const *const FLAC__int32,
        samples: u32,
    ) -> FLAC__bool;
}
extern "C" {
    pub fn FLAC__stream_encoder_process_interleaved(
        encoder: *mut FLAC__StreamEncoder,
        buffer: *const FLAC__int32,
        samples: u32,
    ) -> FLAC__bool;
}
